version: "3"

services:
  zookeeper:
    container_name: local-zookeeper
    image: zookeeper:3.8.0
    ports:
      - 2181:2181
  kafka:
    container_name: local-kafka
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: demo:1:1
  logstash:
    container_name: local-logstash
    image: logstash:8.2.0
    ports:
      - 5000:5000
      - 9600:9600
  elasticsearch:
    container_name: local-elasticsearch
    image: elasticsearch:8.2.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
  kibana:
    container_name: local-kibana
    image: kibana:8.2.0
    ports:
      - 5601:5601
