server:
  name: kibana
  host: "0.0.0.0"
elasticsearch:
  hosts:
    - http://elasticsearch:9200
  serviceAccountToken: "edited"
xpack:
  monitoring:
    ui:
      container:
        elasticsearch:
          enabled: true